services:

  postgres:
    image: postgres:15
    container_name: restaurant_reservation_postgres
    environment:
      POSTGRES_DB: restaurant_reservation_db
      POSTGRES_USER: restaurant_reservation_user
      POSTGRES_PASSWORD: "RRpassword1234!"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: restaurant_reservation_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant_reservation_db
      SPRING_DATASOURCE_USERNAME: restaurant_reservation_user
      SPRING_DATASOURCE_PASSWORD: "RRpassword1234!"
    ports:
      - "8080:8080"

volumes:
  postgres_data: