spring.application.name=restaurant-reservation-system-backend-spring

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_reservation_db
spring.datasource.username=restaurant_reservation_user
spring.datasource.password=RRpassword1234!

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional: show SQL
spring.jpa.show-sql=true

# Spring security
spring.security.user.name=admin
spring.security.user.password=admin1234!

# CORS origins
cors.allowed-origins=http://localhost:3000,http://localhost:4200,http://localhost:5173